"""Tests for record command."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from scripts.commands import record


def test_record_success(tmp_path, monkeypatch):
    monkeypatch.setattr(record, "build_memory_path", lambda cid: str(tmp_path / f"{cid}.md"))
    monkeypatch.setattr(record, "build_customer_dir", lambda cid: str(tmp_path / cid))
    monkeypatch.setattr(record, "get_language", lambda cid: "en")
    result = record.run("OPC-001", {"content": "Shipped MVP today", "day": 5})
    assert result["status"] == "success"
    assert result["result"]["day"] == 5
    assert result["result"]["entry_id"].startswith("JE-")
    assert result["result"]["language"] == "en"


def test_record_success_en(tmp_path, monkeypatch):
    monkeypatch.setattr(record, "build_memory_path", lambda cid: str(tmp_path / f"{cid}.md"))
    monkeypatch.setattr(record, "build_customer_dir", lambda cid: str(tmp_path / cid))
    monkeypatch.setattr(record, "get_language", lambda cid: "en")
    result = record.run("OPC-001", {"content": "Shipped MVP today", "day": 5})
    assert result["status"] == "success"
    assert "Entry" in result["message"]
    assert result["result"]["entry_id"].startswith("JE-")


def test_record_auto_emotion_field_empty(tmp_path, monkeypatch):
    # Emotion descriptions are no longer auto-generated by the skill.
    monkeypatch.setattr(record, "build_memory_path", lambda cid: str(tmp_path / f"{cid}.md"))
    monkeypatch.setattr(record, "build_customer_dir", lambda cid: str(tmp_path / cid))
    result = record.run("OPC-001", {"content": "Felt very happy, finally got it done, especially excited", "day": 2})
    path = tmp_path / "OPC-001.md"
    content = path.read_text()
    # The content itself is preserved; emotion field in frontmatter is left empty unless caller provides it.
    assert "Felt very happy, finally got it done, especially excited" in content


def test_record_missing_content():
    result = record.run("OPC-001", {})
    assert result["status"] == "error"
    assert "content is required" in result["message"]


def test_record_writes_file(tmp_path, monkeypatch):
    path = tmp_path / "OPC-001.md"
    monkeypatch.setattr(record, "build_memory_path", lambda cid: str(path))
    monkeypatch.setattr(record, "build_customer_dir", lambda cid: str(tmp_path / cid))
    record.run("OPC-001", {"content": "Fixed bug", "day": 2})
    assert path.exists()
    assert "Fixed bug" in path.read_text()
    assert "emotion:" in path.read_text()


def test_record_creates_bak(tmp_path, monkeypatch):
    path = tmp_path / "OPC-001.md"
    monkeypatch.setattr(record, "build_memory_path", lambda cid: str(path))
    monkeypatch.setattr(record, "build_customer_dir", lambda cid: str(tmp_path / cid))
    record.run("OPC-001", {"content": "First version", "day": 1})
    assert path.exists()
    record.run("OPC-001", {"content": "Second version", "day": 1})
    bak_path = path.with_suffix(".md.bak")
    assert bak_path.exists()
    assert "First version" in bak_path.read_text()
    assert "Second version" in path.read_text()
